name: Publish Package
on:
    workflow_dispatch:

permissions:
    id-token: write # Required for OIDC
    contents: write

jobs:
    publish:
        uses: DCC-BS/ci-workflows/.github/workflows/npm-publish.yml@814649735835a84a3d0d6c8d6e6db87dfeb8b348 # v8
        with:
            install_command: bun install
            build_command: bun run generate
            prepack_command: bun run prepack
