name: Publish Package
on:
    workflow_dispatch:

permissions:
    id-token: write # Required for OIDC
    contents: write

jobs:
    publish:
        uses: DCC-BS/ci-workflows/.github/workflows/npm-publish.yml@52f8293531f9389c887c7d14c2b57d90d12ef9ae # v9
        with:
            install_command: bun install
            build_command: bun run generate
            prepack_command: bun run prepack
